config/routes.rb
Rails.application.routes.draw do
  resources :guests
  root 'guests#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :guests

  validates :name,
            presence: {
              message: 'É necessário selecionar uma Categoria para criar um Participante.'
            }
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  belongs_to :category
  has_many :phones, dependent: :destroy

  accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true

  validates :name,
            presence: {
              message: 'É necessário preencher o campo Nome para criar um Participante.'
            },
            format: {
              with: /[A-Za-z ]/,
              message: 'Apenas letras são permitidas no campo Nome.'
            }

  validates :age,
            presence: {
              message: 'É necessário preencher o campo Idade para criar um Participante.'
            },
            numericality: {
              less_than_or_equal_to: 120,
              only_integer: true,
              message: 'Apenas números inteiros abaixo de 120 são permitidos no campo Idade.'
            }

  validates :gender,
            presence: {
              message: 'É necessário selecionar um Gênero para criar um Participante.'
            }

  validates :street,
            presence: {
              message: 'É necessário preencher o campo Rua para criar um Participante.'
            },
            format: {
              with: /[A-Za-z0-9 ]/,
              message: 'Apenas letras e números são permitidas no campo Rua.'
            }

  validates :neighborhood,
            presence: {
              message: 'É necessário preencher o campo Bairro para criar um Participante.'
            },
            format: {
              with: /[A-Za-z0-9 ]/,
              message: 'Apenas letras e números são permitidas no campo Bairro.'
            }

  validates :cep,
            presence: {
              message: 'É necessário preencher o campo CEP para criar um Participante.'
            },
            format: {
              with: /[0-9]-/,
              message: 'Apenas números são permitidos no campo CEP.'
            },
            length: {
              minimum: 9,
              message: 'O CEP deve possuir 8 digitos.'
            }

  validates :street_number,
            presence: {
              message: 'É necessário preencher o campo Número para criar um Participante.'
            },
            numericality: {
              only_integer: true,
              message: 'Apenas números inteiros são permitidos no campo Número.'
            }

  validates :state,
            presence: {
              message: 'É necessário selecionar um Estado para criar um Participante.'
            }
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :guest
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: %i[show edit update destroy]
  before_action :selections, only: %i[create new edit update show]

  # GET /guests
  # GET /guests.json
  def index
    @guests = Guest.all
  end

  # GET /guests/1
  # GET /guests/1.json
  def show; end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit; end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: 'Participante criado com sucesso!' }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to guests_path, notice: 'Participante editado com sucesso!' }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url, notice: 'Participante excluido com sucesso' }
      format.json { head :no_content }
    end
  end

  def selections
    @category_selection = Category.all
    @gender_selection = %w[Masculino Feminino Outros]
    @state_selection = %w[
      Acre
      Alagoas
      Amapá
      Amazonas
      Bahia
      Ceará
      Distrito\ Federal
      Espírito\ Santo
      Goiás
      Maranhão
      Mato\ Grosso
      Mato\ Grosso\ do\ Sul
      Minas\ Gerais
      Pará
      Paraíba
      Paraná
      Pernambuco
      Piauí
      Rio\ de\ Janeiro
      Rio\ Grande\ do\ Norte
      Rio\ Grande\ do\ Sul
      Rondônia
      Roraima
      Santa\ Catarina
      São\ Paulo
      Sergipe
      Tocantins
    ]
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_guest
    @guest = Guest.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def guest_params
    params.require(:guest).permit(:name,
                                  :age,
                                  :gender,
                                  :category_id,
                                  :street,
                                  :neighborhood,
                                  :cep,
                                  :street_number,
                                  :state,
                                  phones_attributes: %i[id phone _destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, form, association, locals = {})
    new_object = form.object.send(association).klass.new
    id = new_object.object_id
    fields = form.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + '_fields', f: builder)
    end
    link_to(name, '#', class: locals[:class] + ' add_fields', data: { id: id, fields: fields.gsub('\n', '') })
  end
end

app/views/guests/_form.html.erb
<div class='container-fluid'>
  <% if @guest.errors.any? %>
  <div id='error_explanation'>
    <div class='alert alert-danger'>
      <% @guest.errors.full_messages.each do |message| %>
      <%= message %><br>
      <% end %>
    </div>
  </div>
  <% end %>
  <%= form_for(@guest) do |f| %>
  <div class='row row-cols-3' id='form'>
    <div class='col-12 text-light' id='form-name'>
      <%= f.label :name, id:'label-name'%>
      <%= f.text_field :name, class: 'form-control', maxlength: 100, type: 'name', id:'input-name' %>
    </div>
    <div class='col-2 text-light'>
      <%= f.label :age, id:'label-age' %>
      <%= f.text_field :age, class: 'form-control', type: 'numeric', maxlength: 3, id:'input-age' %>
    </div>
    <div class='col-5 text-light'>
      <%= f.label :gender, id:'label-gender' %>
      <%= f.select :gender, @gender_selection, { include_blank: true }, 
        class: 'form-control', id:'select-gender'%>
    </div>
    <div class='col-5 text-light'>
      <%= f.label :category, id:'label-category' %>
      <%= f.collection_select(:category_id, @category_selection, :id, 
        :name, {include_blank: true}, class: 'form-control', id:'select-category')%>
    </div>
    <div class='col-5 text-light'>
      <%= f.label :neighborhood, id:'label-neighborhood' %>
      <%= f.text_field :neighborhood, class: 'form-control', maxlength: 100, type: 'text', id:'input-neighborhood'%>
    </div>
    <div class='col-5 text-light'>
      <%= f.label :state, id:'label-state' %>
      <%= f.select :state, @state_selection, { include_blank: true }, class: 'form-control', id:'select-gender'%>
    </div>
    <div class='col-2 text-light'>
      <%= f.label :cep, id:'label-cep' %>
      <%= f.text_field :cep, class: 'cep form-control', type: 'numeric', id:'input-cep'%>
    </div>
    <div class='col-5 text-light'>
      <%= f.label :street, id:'label-street' %>
      <%= f.text_field :street, class: 'form-control', maxlength: 100, id:'input-street' %>
    </div>
    <div class='col-2 text-light'>
      <%= f.label :street_number, id:'label-street_number' %>
      <%= f.text_field :street_number, class: 'form-control', type: 'numeric', maxlength: 10, id:'input-street_number' %>
    </div>
  </div>
  <div id='div-phones'>
    <%= f.fields_for :phones do |phone_form| %>
    <%= render 'phone_fields', f: phone_form %>
    <% end %>

    <div class='text-light'>
      <%= link_to_add_fields t('add_phone'), f, :phones, class: 'btn border text-light m-3', id:'btn-add_fields'%>
    </div>
  </div>
  <div class='row' id='actions'>
    <div class='col-5' id='div-back'>
      <%= link_to t('back'), guests_path, class: 'btn border text-light', id:'back' %>
    </div>
    <div class='col-7 text-right' id='div-submit'>
      <%= f.submit class: 'btn border text-light', id:'submit' %>
    </div>
  </div>
</div>
<% end %>

app/views/guests/_phone_fields.html.erb
<div class='nested-fields' id='nested-fields'>
  <div class='col-6'>
    <%= f.hidden_field :_destroy %>
    <div class='row align-items-end' id='form-phones'>
      <div class='col-8 text-light' id='div-phones'>
        <%= f.label t('phone'), id: 'label-phone'%>
        <%= f.text_field :phone, class:'phone form-control', id: 'input-phone'%>
      </div>
      <div class='col-4'>
        <%= link_to t('remove'), '#', class: 'btn text-light border', id: 'remove_fields'%>
      </div>
    </div>
  </div>
</div>

app/views/guests/edit.html.erb
<h1 class='text-center text-light'>
  <%= t('edit') + "#{@guest.model_name.human}: #{@guest.name.split.first} "+ 
    "#{@guest.name.split.last != @guest.name.split.first ? @guest.name.split.last : ''}" %>
</h1>

<%= render 'form' %>

app/views/guests/index.html.erb
<% unless notice.nil? %>
<p id='notice' , class='alert alert-success'><%= notice %></p>
<% end %>

<h1 class='text-light'><%= t('list_of') + @guests.model_name.human(count: @guests.count) %></h1>

<%= link_to t('new_guest'), new_guest_path, class: 'btn btn-lg border text-light m-2'  %>
<div class="table-responsive">

  <table class='table text-light mt-3'>
    <thead class='bg-secondary'>
      <tr>
        <th scope="col"><%= @guests.model.human_attribute_name('name') %></th>
        <th scope="col"><%= @guests.model.human_attribute_name('category') %></th>
        <th scope="col"><%= @guests.model.human_attribute_name('state') %></th>
        <th scope="col"><%= t('show') %></th>
        <th scope="col"><%= t('edit') %></th>
        <th scope="col"><%= t('destroy') %></th>

      </tr>
    </thead>

    <tbody>
      <% @guests.each do |guest| %>
      <tr>
        <td><%= guest.name %></td>
        <td><%= guest.category.name %></td>
        <td><%= guest.state %></td>
        <td><%= link_to t('show'), guest, class: 'btn border text-light' %></td>
        <td><%= link_to t('edit'), edit_guest_path(guest), class: 'btn border text-light' %></td>
        <td><%= link_to t('destroy'), guest, method: :delete, data: { confirm: t('sure?', guest: guest.name) }, class: 'btn border text-light' %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/guests/new.html.erb
<h1 class='text-center text-light'><%= t('new') + @guest.model_name.human %></h1>
<%= render 'form' %>

app/views/guests/show.html.erb
<div class='container-fluid'>
  <% unless notice.nil? %>
  <p id="notice" , class='alert alert-success'><%= notice %></p>
  <% end %>
  <%= form_for(@guest) do |f| %>

  <h1 class='text-center text-light'>
    <%= "#{@guest.model_name.human}: #{@guest.name.split.first} "+
      "#{@guest.name.split.last != @guest.name.split.first ? @guest.name.split.last : ''}" %>
  </h1>

  <div class='row row-cols-3'>
    <div class='col-12 text-light'>
      <%= f.label :name %>
      <div class='form-control'><%= @guest.name %></div>
    </div>
    <div class='col-2 text-light'>
      <%= f.label :age %>
      <div class='form-control'><%= @guest.age %></div>
    </div>
    <div class='col-5 text-light'>
      <%= f.label :gender %>
      <div class='form-control'><%= @guest.gender %></div>
    </div>
    <div class='col-5 text-light'>
      <%= f.label :category %>
      <div class='form-control'><%= @guest.category.name %></div>
    </div>
    <div class='col-5 text-light'>
      <%= f.label :neighborhood %>
      <div class='form-control'><%= @guest.neighborhood %></div>
    </div>
    <div class='col-5 text-light'>
      <%= f.label :state %>
      <div class='form-control'><%= @guest.state %></div>
    </div>
    <div class='col-2 text-light'>
      <%= f.label :cep %>
      <div class='form-control'><%= @guest.cep %></div>
    </div>
    <div class='col-5 text-light'>
      <%= f.label :street %>
      <div class='form-control'><%= @guest.street %></div>
    </div>
    <div class='col-2 text-light'>
      <%= f.label :street_number %>
      <div class='form-control'><%= @guest.street_number %></div>
    </div>
  </div>
  <div class='text-light col-5'>
    <% @guest.phones.each do |phone| %>
    <%= f.label :phone %>
    <div class='form-control mb-3 '><%= phone.phone %></div>
    <% end %>
  </div>

  <div class='row'>
    <div class='col'>
      <%= link_to t('back'), guests_path, class: 'btn border text-light mt-3' %>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/_navbar.erb
<nav class="navbar bg-secondary">
  <%= link_to 'CRUD', guests_path, class: 'navbar-brand text-monospace font-weight-bold text-light m-0', id: 'brand' %>
</nav>

app/views/layouts/_navigation.html.erb
<nav class="navbar bg-secondary">
  <%= link_to 'CRUD', guests_path, class: 'navbar-brand text-monospace font-weight-bold text-light m-0', id: 'brand' %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>CRUD de Eventos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class='container-fluid p-0 bg-primary rounded vh-100'>
    <div id='navbar'>
      <%= render 'layouts/navbar' %>
    </div>
    <div class='p-3' id='content'>
      <%= yield %>
    </div>
  </div>
</body>

</html>